#!/bin/sh
#
# Makeall  --  Print message about making all of Xinu
#
echo
echo '*** Making '"`pwd`"'/src/sys/config'
echo

(cd config && make && make install)
#/bin/ranlib11 ../lib/libx.a

echo '*************************************************************'
echo '*************************************************************'
echo '***                                                       ***'
echo '***                       N O T E                         ***'
echo '***       To make all of Xinu, change to directory        ***'
echo '***       $XINU/src/sys/sys and look at the file          ***'
echo '***       Configuration.  If your 68008 has a standard    ***'
echo '***       hardware configuration you may not need to      ***'
echo '***       recompile at all.                               ***'
echo '***                                                       ***'
echo '*************************************************************'
echo '*************************************************************'
