#!/bin/sh
#
# Makeall -- make all of src/cmd for Xinu
#

echo
echo '*** Making commands in {Xinu-directory}/src/cmd'

make && make install
for d in download fs
do
	echo
	echo "*** Making commands in $XINU/src/cmd/$i"
	(cd $d && make && make install)
done
