#!/bin/sh
#
# Makeall -- make the standalone server for Xinu
#
echo
echo '*** Making serve68, the standalone server'
for d in config sys
do
	echo
        echo "*** Making programs in $XINU/src/serve68/$d"

	(cd $d && make && make install)
done
