#!/bin/sh
#
# Makeall -- make all pieces of Xinu cross-development system
#

echo '*** Making all pieces of Xinu cross-development system'
echo

for d in cmd lib serve68 sys
do
	(cd $d && sh Makeall)
done
